[build]
builder = "NIXPACKS"
nixpacksVersion = "1.17.0"
buildCommand = "npm run build"

[deploy]
numReplicas = 1
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 